name: Build and Publish

on:
    push:
        branches:
            - main
        paths:
            - '**.json'
            - '**.js'
            - '**.yml'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Install dependencies
              run: npm install
            - uses: ./
            - name: Run tests
              run: npm run test
            - uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
              with:
                  args: --acl public-read --follow-symlinks
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SOURCE_DIR: 'generated'
                  DEST_DIR: 'trackerblocking/config'
            - name: Set version variable
              run: echo "VERSION=$(jq -r .version ./generated/v5/extension-config.json)" >> $GITHUB_ENV
            - name: Generate release description file
              uses: ./scripts/
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  type: zip
                  filename: privacy-configuration.zip
                  path: generated
            - uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174
              with:
                  token: '${{ secrets.GITHUB_TOKEN }}'
                  name: 'remote-privacy-config-${{ env.VERSION }}'
                  artifacts: privacy-configuration.zip
                  tag: ${{ env.VERSION }}
                  bodyFile: etags.md
